spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workout_manager
    username: root
    password: YourPassword

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: YourId
            client-secret: YourSecret
            scope: email, profile

jwt:
  secret: workoutmanagersecretkeyworkoutmanager
  access-expiration: 900000
  refresh-expiration: 604800000
