spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workout_manager
    username: root
    password: Pratiksha

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 55102257680-is7jr9edj5271l0mkqd159f6tcist8fp.apps.googleusercontent.com
            client-secret: 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
            scope: email, profile

jwt:
  secret: workoutmanagersecretkeyworkoutmanager
  access-expiration: 900000
  refresh-expiration: 604800000
